import React, { useState, useEffect } from 'react';
import GlassPanel from './GlassPanel';
import { 
    CpuChipIcon, PlayIcon, StopIcon, CheckCircle2Icon, 
    SettingsIcon, AtomIcon, PlusIcon, ZapIcon,
    ChartBarIcon, LoaderIcon, ActivityIcon, AlertTriangleIcon, Share2Icon,
    RefreshCwIcon, FastForwardIcon
} from './Icons';
import { useSimulation } from '../context/SimulationContext';
import { useToast } from '../context/ToastContext';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';

interface QuantumDeepLearningProps {
    onApplyPatch?: (filePath: string, content: string) => void;
}

const QDLLayerBlock: React.FC<{ layer: { type: string, coherence: number }, index: number, isTraining: boolean }> = ({ layer, index, isTraining }) => {
    const [opacities] = useState(() => Array.from({ length: 12 }).map(() => 0.3 + Math.random() * 0.7));
    const typeColors = {
        'ENCODING': 'from-blue-600/40 to-blue-900/40 border-blue-400/50 text-blue-200',
        'QCNN': 'from-purple-600/40 to-purple-900/40 border-purple-400/50 text-purple-200',
        'POOLING': 'from-pink-600/40 to-pink-900/40 border-pink-400/50 text-pink-200',
        'DENSE': 'from-cyan-600/40 to-cyan-900/40 border-cyan-400/50 text-cyan-200'
    };

    return (
        <div 
            className={`relative p-3 rounded-lg border bg-gradient-to-br ${typeColors[layer.type as keyof typeof typeColors]} transition-all duration-500 flex flex-col group shadow-lg mb-4 last:mb-0`}
            style={{ 
                transform: `translateZ(${index * 20}px)`,
                boxShadow: isTraining ? `0 0 15px rgba(255, 255, 255, 0.1)` : 'none'
            }}
        >
            <div className="flex justify-between items-center mb-1">
                <span className="text-[10px] font-bold tracking-tighter uppercase opacity-80">Stack Layer L{index}</span>
                <span className="text-[9px] font-mono bg-black/40 px-1.5 rounded">{layer.type}</span>
            </div>
            
            <div className="flex items-center justify-between">
                <div className="flex gap-0.5">
                    {Array.from({ length: 12 }).map((_, i) => (
                        <div 
                            key={i} 
                            className={`w-1 h-4 rounded-full ${isTraining ? 'animate-pulse' : ''}`}
                            style={{ 
                                backgroundColor: 'currentColor', 
                                opacity: opacities[i],
                                animationDelay: `${i * 0.08}s`
                            }}
                        />
                    ))}
                </div>
                <div className="text-right">
                    <p className="text-[8px] opacity-60 uppercase font-bold">Fidelity</p>
                    <p className={`text-[10px] font-mono ${layer.coherence < 0.9 ? 'text-yellow-400' : 'text-green-300'}`}>
                        {(layer.coherence * 100).toFixed(1)}%
                    </p>
                </div>
            </div>

            <div className="absolute -bottom-4 left-1/2 -translate-x-1/2 w-0.5 h-4 bg-white/10 group-last:hidden"></div>
        </div>
    );
};

const QuantumDeepLearning: React.FC<QuantumDeepLearningProps> = ({ onApplyPatch }) => {
    const { qdlEngine, startQDLTraining, stopQDLTraining, setQDLStrategy, addQDLLayer } = useSimulation();
    const { addToast } = useToast();
    const [isAutoEvolving, setIsAutoEvolving] = useState(false);

    const dimensionality = Math.pow(2, qdlEngine.qubitCount).toExponential(2);

    // Auto-Evolve Loop
    useEffect(() => {
        let timer: ReturnType<typeof setTimeout>;
        
        if (isAutoEvolving) {
            if (qdlEngine.status === 'IDLE') {
                timer = setTimeout(() => {
                    startQDLTraining();
                }, 1500);
            } else if (qdlEngine.status === 'CONVERGED') {
                timer = setTimeout(() => {
                    // Logic to "patch"
                    const patch = `/**
 * AUTO-EVOLVED QDL HIERARCHY
 * Generated by Agent Q QNN Evolution Hub
 * Accuracy: ${(qdlEngine.accuracy * 100).toFixed(4)}%
 * Loss: ${qdlEngine.loss.toFixed(6)}
 * Timestamp: ${new Date().toISOString()}
 */

export const OPTIMIZED_STACK_CONFIG = {
    hilbert_space: "${dimensionality}",
    stack_depth: ${qdlEngine.layers.length},
    layers: ${JSON.stringify(qdlEngine.layers, null, 2)}
};

// Evolution converged to global minimum. Applying kernel hot-swap...
`;
                    if (onApplyPatch) {
                        onApplyPatch('qdl_hierarchy_evolved.q', patch);
                        addToast("QDL: Auto-patching evolved hierarchy to Source Nexus.", "success");
                    }
                    
                    // Reset to start next loop cycle
                    stopQDLTraining();
                }, 3000);
            }
        }
        
        return () => clearTimeout(timer);
    }, [isAutoEvolving, qdlEngine.status, qdlEngine.accuracy, qdlEngine.loss, qdlEngine.layers, dimensionality, onApplyPatch, startQDLTraining, stopQDLTraining, addToast]);

    return (
        <GlassPanel title={
            <div className="flex items-center justify-between w-full">
                <div className="flex items-center">
                    <AtomIcon className="w-5 h-5 mr-2 text-blue-400" />
                    <span>Parameterized Quantum Deep Learning (PQDL)</span>
                </div>
                <div className="flex items-center gap-2 mr-2">
                    {isAutoEvolving && (
                        <div className="flex items-center gap-1.5 text-[8px] font-bold text-pink-400 bg-pink-900/20 px-2 py-0.5 rounded border border-pink-800 animate-pulse">
                            <FastForwardIcon className="w-2.5 h-2.5" /> RECURSIVE_EVOLUTION
                        </div>
                    )}
                    {qdlEngine.status === 'TRAINING' && !isAutoEvolving && (
                        <div className="flex items-center gap-1.5 text-[8px] font-bold text-blue-400 bg-blue-900/20 px-2 py-0.5 rounded border border-blue-800 animate-pulse">
                            <Share2Icon className="w-2.5 h-2.5" /> UPLINK: QNN_CORE
                        </div>
                    )}
                    <span className={`text-[10px] px-2 py-0.5 rounded border font-mono ${qdlEngine.status === 'TRAINING' ? 'bg-blue-900/30 border-blue-500 text-blue-300 animate-pulse' : 'bg-gray-800 border-gray-600 text-gray-500'}`}>
                        {qdlEngine.status === 'TRAINING' ? 'OPTIMIZING HIERARCHY' : 'IDLE'}
                    </span>
                </div>
            </div>
        }>
            <div className="flex flex-col h-full gap-4 p-4 animate-fade-in overflow-hidden">
                <div className="grid grid-cols-4 gap-4 flex-shrink-0">
                    <div className="bg-black/40 border border-blue-900/50 rounded p-2 text-center relative overflow-hidden group">
                        <div className="absolute inset-0 bg-blue-500/5 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                        <p className="text-[9px] text-blue-400 uppercase font-bold tracking-widest mb-1">Hilbert Space</p>
                        <p className="text-lg font-mono text-white">{dimensionality}</p>
                    </div>
                    <div className="bg-black/40 border border-purple-900/50 rounded p-2 text-center">
                        <p className="text-[9px] text-purple-400 uppercase font-bold tracking-widest mb-1">Stack Depth</p>
                        <p className="text-lg font-mono text-white">{qdlEngine.layers.length}</p>
                    </div>
                    <div className="bg-black/40 border border-cyan-900/50 rounded p-2 text-center">
                        <p className="text-[9px] text-cyan-400 uppercase font-bold tracking-widest mb-1">Accuracy</p>
                        <p className="text-lg font-mono text-green-400">{(qdlEngine.accuracy * 100).toFixed(2)}%</p>
                    </div>
                    <div className="bg-black/40 border border-red-900/50 rounded p-2 text-center">
                        <p className="text-[9px] text-red-400 uppercase font-bold tracking-widest mb-1">Cost (L2)</p>
                        <p className="text-lg font-mono text-red-400">{qdlEngine.loss.toFixed(4)}</p>
                    </div>
                </div>

                <div className="flex-grow grid grid-cols-1 md:grid-cols-3 gap-4 min-h-0">
                    <div className="col-span-1 flex flex-col gap-2 min-h-0">
                        <p className="text-[10px] text-blue-500 font-bold uppercase tracking-widest px-1">Dimensional Hierarchy</p>
                        <div className="flex-grow bg-black/30 border border-blue-800/30 rounded-lg overflow-y-auto custom-scrollbar p-4 perspective-container" style={{ perspective: '800px' }}>
                            <div className="flex flex-col transform-style-preserve-3d transition-transform duration-500">
                                {qdlEngine.layers.map((layer, idx) => (
                                    <QDLLayerBlock key={idx} layer={layer} index={idx} isTraining={qdlEngine.status === 'TRAINING'} />
                                ))}
                            </div>
                        </div>
                        <div className="bg-black/40 border border-cyan-900/30 p-2 rounded flex gap-2 overflow-x-auto no-scrollbar">
                             {['QCNN', 'POOLING', 'DENSE'].map(type => (
                                 <button key={type} onClick={() => addQDLLayer(type as any)} className="flex-1 whitespace-nowrap bg-blue-900/20 border border-blue-700/50 hover:bg-blue-800/40 text-[9px] font-bold text-blue-200 py-1.5 px-2 rounded flex items-center justify-center gap-1 transition-all"><PlusIcon className="w-3 h-3" /> {type}</button>
                             ))}
                        </div>
                    </div>

                    <div className="col-span-2 flex flex-col gap-4 min-h-0">
                        <div className="flex-grow grid grid-cols-2 gap-4 min-h-0">
                            <div className="bg-black/30 p-4 rounded-lg border border-blue-900/50 flex flex-col gap-4 relative overflow-hidden">
                                {isAutoEvolving && <div className="absolute top-0 right-0 p-2"><RefreshCwIcon className="w-4 h-4 text-pink-500 animate-spin" /></div>}
                                <h4 className="text-xs font-bold text-white mb-2 uppercase flex items-center gap-2 border-b border-blue-800/50 pb-2"><SettingsIcon className="w-4 h-4 text-blue-400" /> Training Hub</h4>
                                <div className="space-y-2">
                                    <button onClick={() => setQDLStrategy('LAYER-WISE')} className={`w-full p-2.5 rounded border text-[10px] font-bold text-left transition-all ${qdlEngine.trainingStrategy === 'LAYER-WISE' ? 'bg-blue-600/40 border-blue-400 text-white shadow-lg shadow-blue-900' : 'bg-black/40 border-blue-900 text-blue-600 hover:bg-blue-900/20'}`}>
                                        <div className="flex justify-between items-center"><span>Hierarchical Layer-Wise</span>{qdlEngine.trainingStrategy === 'LAYER-WISE' && <CheckCircle2Icon className="w-3 h-3" />}</div>
                                    </button>
                                    <button onClick={() => setQDLStrategy('GLOBAL')} className={`w-full p-2.5 rounded border text-[10px] font-bold text-left transition-all ${qdlEngine.trainingStrategy === 'GLOBAL' ? 'bg-purple-600/40 border-purple-400 text-white shadow-lg shadow-purple-900' : 'bg-black/40 border-purple-900 text-purple-600 hover:bg-blue-900/20'}`}>
                                        <div className="flex justify-between items-center"><span>Global State Optimization</span>{qdlEngine.trainingStrategy === 'GLOBAL' && <CheckCircle2Icon className="w-3 h-3" />}</div>
                                    </button>
                                </div>
                                <div className="mt-auto space-y-2">
                                    <button 
                                        onClick={() => setIsAutoEvolving(!isAutoEvolving)} 
                                        className={`w-full py-2.5 rounded text-[10px] font-bold flex items-center justify-center gap-2 transition-all border ${isAutoEvolving ? 'bg-pink-600/30 border-pink-500 text-pink-200' : 'bg-black/40 border-pink-900 text-pink-500 hover:bg-pink-900/20'}`}
                                    >
                                        <RefreshCwIcon className={`w-3.5 h-3.5 ${isAutoEvolving ? 'animate-spin' : ''}`} /> 
                                        {isAutoEvolving ? 'AUTO-EVOLVE: ACTIVE' : 'ENABLE AUTO-EVOLVE'}
                                    </button>
                                    <button 
                                        onClick={() => qdlEngine.status === 'TRAINING' ? stopQDLTraining() : startQDLTraining()} 
                                        disabled={isAutoEvolving}
                                        className={`w-full py-3 rounded text-xs font-bold flex items-center justify-center gap-2 transition-all ${isAutoEvolving ? 'opacity-30 cursor-not-allowed' : qdlEngine.status === 'TRAINING' ? 'bg-red-900/30 border-red-500 text-red-200' : 'bg-green-600/20 border-green-500 text-green-300'}`}
                                    >
                                        {qdlEngine.status === 'TRAINING' ? <StopIcon className="w-4 h-4" /> : <PlayIcon className="w-4 h-4" />}
                                        {qdlEngine.status === 'TRAINING' ? 'SUSPEND SIMULATION' : 'INITIALIZE GRADIENT MAP'}
                                    </button>
                                </div>
                            </div>
                            <div className="bg-black/30 p-4 rounded-lg border border-blue-900/50 flex flex-col overflow-hidden relative">
                                <p className="text-[10px] text-blue-400 uppercase font-bold tracking-widest mb-3 flex items-center justify-between">
                                    <span>Gradient Signal</span>
                                    {qdlEngine.status === 'TRAINING' && <ActivityIcon className="w-3 h-3 animate-pulse text-blue-500" />}
                                </p>
                                <div className="flex-grow min-h-0 relative">
                                    <ResponsiveContainer width="100%" height="100%">
                                        <AreaChart data={qdlEngine.logs.filter(l => l.includes('Signal')).map((l, i) => ({ step: i, sig: parseFloat(l.split('Signal: ')[1]) }))}>
                                            <XAxis dataKey="step" hide /><YAxis domain={[0, 1]} hide /><Area type="monotone" dataKey="sig" stroke="#3b82f6" strokeWidth={2} fill="#3b82f6" fillOpacity={0.2} isAnimationActive={false} />
                                        </AreaChart>
                                    </ResponsiveContainer>
                                </div>
                                <div className="mt-2 h-16 bg-black/40 border border-blue-900/30 rounded p-1.5 font-mono text-[8px] text-blue-300/60 overflow-y-auto custom-scrollbar">
                                    {qdlEngine.logs.slice(-5).map((log, i) => <div key={i} className="truncate">{log}</div>)}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </GlassPanel>
    );
};

export default QuantumDeepLearning;